export function audio(){
    return {
        audio: [{
            title: '清水er',
            artist: '大天蓬',
            src: 'http://music.ruoyi.vip/datianpeng',
            pic: './music/pic/qingshui.jpg',
            theme: '#ebd0c2'
        }, {
            title: '醉倾城',
            artist: '小阿枫',
            src: 'http://music.ruoyi.vip/zuiqingcheng',
            pic: './music/pic/xiaoafeng.jpg',
            theme: '#46718b'
        }, {
            title: '不过人间',
            artist: '海来阿木',
            src: 'http://music.ruoyi.vip/buguorenjian',
            pic: './music/pic/hailaiamu.jpg',
            theme: '#46718b'
        }, {
            title: '笑纳',
            artist: '花僮',
            src: 'http://music.ruoyi.vip/xiaona',
            pic: './music/pic/huatong.jpg',
            theme: '#ebd0c2'
        }, {
            title: '游京',
            artist: '海伦',
            src: 'http://music.ruoyi.vip/youjin',
            pic: './music/pic/hailun.jpg',
            theme: '#46718b'
        }, {
            title: '忘川彼岸',
            artist: '零一九零贰',
            src: 'http://music.ruoyi.vip/wangchuangbian',
            pic: './music/pic/01902.jpg',
            theme: '#46718b'
        }, {
            title: '游山恋',
            artist: '海伦',
            src: 'http://music.ruoyi.vip/youshanlian',
            pic: './music/pic/hailun.jpg',
            theme: '#46718b'
        }, {
            title: '光明',
            artist: '赵梓婷',
            src: 'http://music.ruoyi.vip/guangming',
            pic: './music/pic/zhaoziting.jpg',
            theme: '#ebd0c2'
        }, {
            title: '兄弟想你了',
            artist: '潇公子',
            src: 'http://music.ruoyi.vip/xiongdixiangnile',
            pic: './music/pic/xiaogongzi.jpg',
            theme: '#46718b'
        }, {
            title: '飞鸟和蝉',
            artist: '任然',
            src: 'http://music.ruoyi.vip/feiniaohechan',
            pic: './music/pic/renran.jpg',
            theme: '#ebd0c2'
        }, {
            title: '你快听滴答滴',
            artist: '龙儿',
            src: 'http://ruoyi.vip/music/mp3/龙儿 - 你快听滴答滴.mp3',
            pic: './music/pic/longer.jpg',
            theme: '#46718b'
        }, {
            title: '热火斯卡拉',
            artist: '承利',
            src: 'http://music.ruoyi.vip/rehuosikala',
            pic: './music/pic/chengli.jpg',
            theme: '#46718b'
        }, {
            title: '凤舞九天',
            artist: '承利',
            src: 'http://music.ruoyi.vip/fengwujiutian',
            pic: './music/pic/chengli.jpg',
            theme: '#46718b'
        }, {
            title: '春庭雪',
            artist: '等什么君',
            src: 'http://music.ruoyi.vip/chuntingxue',
            pic: './music/pic/dengshenmejun.jpg',
            theme: '#ebd0c2'
        }, {
            title: '夏天的风',
            artist: 'Uu',
            src: 'http://music.ruoyi.vip/xiatiandefeng',
            pic: './music/pic/uu.jpg',
            theme: '#ebd0c2'
        }, {
            title: '微微',
            artist: '傅如乔',
            src: 'http://music.ruoyi.vip/weiwei',
            pic: './music/pic/furuqiao.jpg',
            theme: '#ebd0c2'
        }, {
            title: '你若三冬',
            artist: '阿悠悠',
            src: 'http://music.ruoyi.vip/niruosandong',
            pic: './music/pic/ayouyou.jpg',
            theme: '#ebd0c2'
        }, {
            title: '一生与你擦肩而过',
            artist: '阿悠悠',
            src: 'http://music.ruoyi.vip/ysyncjeg',
            pic: './music/pic/ayouyou.jpg',
            theme: '#ebd0c2'
        }, {
            title: '再见只是陌生人',
            artist: '庄心妍',
            src: 'http://music.ruoyi.vip/zjzsmsr',
            pic: './music/pic/zhuangxinyan.jpg',
            theme: '#ebd0c2'
        }, {
            title: '无人之岛',
            artist: '任然',
            src: 'http://music.ruoyi.vip/wurenzhidao',
            pic: './music/pic/renran.jpg',
            theme: '#ebd0c2'
        }, {
            title: '辞九门回忆',
            artist: '等什么君',
            src: 'http://music.ruoyi.vip/cijiumenhuiyi',
            pic: './music/pic/dengshenmejun.jpg',
            theme: '#ebd0c2'
        }, {
            title: '惊雷',
            artist: '皮卡丘多多',
            src: 'http://music.ruoyi.vip/jinglei',
            pic: './music/pic/pikaqiuduoduo.jpg',
            theme: '#ebd0c2'
        }, {
            title: '旧梦一场',
            artist: '阿悠悠',
            src: 'http://music.ruoyi.vip/jiumengyichang',
            pic: './music/pic/ayouyou.jpg',
            theme: '#ebd0c2'
        }, {
            title: '想起了你',
            artist: '程响',
            src: 'http://music.ruoyi.vip/xiangqileni',
            pic: './music/pic/chengxiang.jpg',
            theme: '#ebd0c2'
        }, {
            title: '回到夏天',
            artist: '爱写歌的小田,傲七爷',
            src: 'http://music.ruoyi.vip/huidaoxiatian',
            pic: './music/pic/aoqiye.jpg',
            theme: '#ebd0c2'
        }, {
            title: '苏幕遮',
            artist: '张晓棠',
            src: 'http://music.ruoyi.vip/shuzhemu',
            pic: './music/pic/zhangxiaotang.jpg',
            theme: '#ebd0c2'
        }, {
            title: '万有引力',
            artist: 'Fyy',
            src: 'http://music.ruoyi.vip/wanyouyinli',
            pic: './music/pic/fyy.jpg',
            theme: '#ebd0c2'
        }, {
            title: '莫问归期',
            artist: '蒋雪儿',
            src: 'http://music.ruoyi.vip/mowenguiqi',
            pic: './music/pic/jiangxueer.jpg',
            theme: '#ebd0c2'
        }, {
            title: '点歌的人',
            artist: '海来阿木',
            src: 'http://music.ruoyi.vip/diangederen',
            pic: './music/pic/hailaiamu.jpg',
            theme: '#46718b'
        }, {
            title: '后来遇见他',
            artist: '胡66',
            src: 'http://music.ruoyi.vip/houlaiyujianta',
            pic: './music/pic/hu66.jpg',
            theme: '#ebd0c2'
        }, {
            title: '赤伶',
            artist: 'HITA',
            src: 'http://music.ruoyi.vip/chiling',
            pic: './music/pic/hita.jpg',
            theme: '#ebd0c2'
        }, {
            title: '嚣张',
            artist: '祁闻冥轩',
            src: 'http://music.ruoyi.vip/xiaozhang',
            pic: './music/pic/qiwenmingxuan.jpg',
            theme: '#46718b'
        }, {
            title: '少年',
            artist: '梦然',
            src: 'http://music.ruoyi.vip/shaonian',
            pic: './music/pic/mengran.jpg',
            theme: '#ebd0c2'
        }, {
            title: '一个人挺好',
            artist: '周森',
            src: 'http://music.ruoyi.vip/yigerentinghao',
            pic: './music/pic/zhoushen.jpg',
            theme: '#ebd0c2'
        }, {
            title: '你笑起来真好看',
            artist: '刘苏萱',
            src: 'http://music.ruoyi.vip/nxqlzhk',
            pic: './music/pic/liusuxuan.jpg',
            theme: '#ebd0c2'
        }, {
            title: '世界这么大还是遇见你',
            artist: '程响',
            src: 'http://music.ruoyi.vip/sjnmdhsyjn',
            pic: './music/pic/chengxiang.jpg',
            theme: '#ebd0c2'
        }, {
            title: '百花香',
            artist: '魏新雨',
            src: 'http://music.ruoyi.vip/baihuaxiang',
            pic: './music/pic/weixinyu.jpg',
            theme: '#ebd0c2'
        }, {
            title: '下山',
            artist: '要不要买菜',
            src: 'http://music.ruoyi.vip/xiashan',
            pic: './music/pic/ybymc.jpg',
            theme: '#46718b'
        }, {
            title: '桥边姑娘',
            artist: '张茜',
            src: 'http://ruoyi.vip/music/mp3/张茜 - 桥边姑娘.mp3',
            pic: './music/pic/zhangqian.jpg',
            theme: '#ebd0c2'
        }, {
            title: '你的答案',
            artist: '阿冗',
            src: 'http://music.ruoyi.vip/nidedaan',
            pic: './music/pic/arong.jpg',
            theme: '#46718b'
        }, {
            title: '生而为人',
            artist: '尚士达',
            src: 'http://music.ruoyi.vip/shengerweiren',
            pic: './music/pic/shangshida.jpg',
            theme: '#46718b'
        }, {
            title: '火红的萨日朗',
            artist: '要不要买菜',
            src: 'http://music.ruoyi.vip/huohongdesarilang',
            pic: './music/pic/ybymc.jpg',
            theme: '#46718b'
        }, {
            title: '画',
            artist: '韩甜甜',
            src: 'http://music.ruoyi.vip/hua',
            pic: './music/pic/hantiantian.jpg',
            theme: '#ebd0c2'
        }, {
            title: '飞云之下',
            artist: '韩甜甜',
            src: 'http://ruoyi.vip/music/mp3/韩甜甜 - 飞云之下.mp3',
            pic: './music/pic/hantiantian.jpg',
            theme: '#ebd0c2'
        }, {
            title: '世间美好与你环环相扣',
            artist: '柏松',
            src: 'http://music.ruoyi.vip/sjmhynhhxk',
            pic: './music/pic/baisong.jpg',
            theme: '#46718b'
        }, {
            title: '大田後生仔',
            artist: '丫蛋蛋',
            src: 'http://music.ruoyi.vip/datianhoushengzai',
            pic: './music/pic/yadandan.jpg',
            theme: '#ebd0c2'
        }, {
            title: '野狼disco',
            artist: '宝石Gem',
            src: 'http://music.ruoyi.vip/yelangdisco',
            pic: './music/pic/gem.jpg',
            theme: '#46718b'
        }, {
            title: '像我这样的人',
            artist: '毛不易',
            src: 'http://music.ruoyi.vip/xwzydr',
            pic: './music/pic/maobuyi.jpg',
            theme: '#46718b'
        }, {
            title: '孤芳自赏',
            artist: '杨小壮',
            src: 'http://music.ruoyi.vip/gufangzishang',
            pic: './music/pic/yangxiaozhuang.jpg',
            theme: '#46718b'
        }, {
            title: '别想她',
            artist: '小阿枫',
            src: 'http://ruoyi.vip/music/mp3/小阿枫 - 别想她.mp3',
            pic: './music/pic/xiaoafeng.jpg',
            theme: '#46718b'
        }, {
            title: '最远的你是我最近的爱',
            artist: '小阿枫',
            src: 'http://music.ruoyi.vip/zydnswzjda',
            pic: './music/pic/xiaoafeng.jpg',
            theme: '#46718b'
        }, {
            title: '想死却又不敢',
            artist: '井胧',
            src: 'http://music.ruoyi.vip/xiangsiqueyoubugan',
            pic: './music/pic/jinglong.jpg',
            theme: '#46718b'
        }, {
            title: '把孤独当做晚餐',
            artist: '南铃子',
            src: 'http://music.ruoyi.vip/bgddzwc',
            pic: './music/pic/nanlingzi.jpg',
            theme: '#ebd0c2'
        }, {
            title: 'Lil Mama',
            artist: 'Jain',
            src: 'http://music.ruoyi.vip/Lil-Mama',
            pic: './music/pic/Jain.jpg',
            theme: '#ebd0c2'
        }, {
            title: '说好不哭',
            artist: '周杰伦',
            src: 'http://music.ruoyi.vip/shuohaobuku',
            pic: './music/pic/zhoujielun.jpg',
            theme: '#46718b'
        }, {
            title: '晴天',
            artist: '周杰伦',
            src: 'http://music.ruoyi.vip/qingtian',
            pic: './music/pic/zhoujielun.jpg',
            theme: '#46718b'
        }, {
            title: '七里香',
            artist: '周杰伦',
            src: 'http://music.ruoyi.vip/qilixiang',
            pic: './music/pic/zhoujielun.jpg',
            theme: '#46718b'
        }, {
            title: '搁浅',
            artist: '周杰伦',
            src: 'http://music.ruoyi.vip/geqian',
            pic: './music/pic/zhoujielun.jpg',
            theme: '#46718b'
        }, {
            title: '夜曲',
            artist: '周杰伦',
            src: 'http://music.ruoyi.vip/yequ',
            pic: './music/pic/zhoujielun.jpg',
            theme: '#46718b'
        }, {
            title: '听妈妈的话',
            artist: '周杰伦',
            src: 'http://music.ruoyi.vip/tingmamadehua',
            pic: './music/pic/zhoujielun.jpg',
            theme: '#46718b'
        }, {
            title: '可爱女人',
            artist: '周杰伦',
            src: 'http://music.ruoyi.vip/keainvren',
            pic: './music/pic/zhoujielun.jpg',
            theme: '#46718b'
        }, {
            title: '简单爱',
            artist: '周杰伦',
            src: 'http://music.ruoyi.vip/jiandanai',
            pic: './music/pic/zhoujielun.jpg',
            theme: '#46718b'
        }, {
            title: '爱在西元前',
            artist: '周杰伦',
            src: 'http://music.ruoyi.vip/aizaiximenqian',
            pic: './music/pic/zhoujielun.jpg',
            theme: '#46718b'
        }, {
            title: '世界末日',
            artist: '周杰伦',
            src: 'http://music.ruoyi.vip/shijiemori',
            pic: './music/pic/zhoujielun.jpg',
            theme: '#46718b'
        }, {
            title: '半岛铁盒',
            artist: '周杰伦',
            src: 'http://music.ruoyi.vip/bandaotiehe',
            pic: './music/pic/zhoujielun.jpg',
            theme: '#46718b'
        }, {
            title: '回到过去',
            artist: '周杰伦',
            src: 'http://music.ruoyi.vip/huidaoguoqu',
            pic: './music/pic/zhoujielun.jpg',
            theme: '#46718b'
        }, {
            title: '轨迹',
            artist: '周杰伦',
            src: 'http://music.ruoyi.vip/guiji',
            pic: './music/pic/zhoujielun.jpg',
            theme: '#46718b'
        }, {
            title: '断了的弦',
            artist: '周杰伦',
            src: 'http://music.ruoyi.vip/duanledexian',
            pic: './music/pic/zhoujielun.jpg',
            theme: '#46718b'
        }, {
            title: '发如雪',
            artist: '周杰伦',
            src: 'http://music.ruoyi.vip/faruxue',
            pic: './music/pic/zhoujielun.jpg',
            theme: '#46718b'
        }, {
            title: '东风破',
            artist: '周杰伦',
            src: 'http://music.ruoyi.vip/dongfengpo',
            pic: './music/pic/zhoujielun.jpg',
            theme: '#46718b'
        }, {
            title: '很任性',
            artist: '兔子牙',
            src: 'http://music.ruoyi.vip/henrenxing',
            pic: './music/pic/tuziya.jpg',
            theme: '#ebd0c2'
        }, {
            title: '小白兔遇上卡布奇诺',
            artist: '兔子牙',
            src: 'http://music.ruoyi.vip/xbtyskbqn',
            pic: './music/pic/tuziya.jpg',
            theme: '#ebd0c2'
        }, {
            title: '红昭愿',
            artist: '音阙诗听',
            src: 'http://music.ruoyi.vip/hongzhaoyuan',
            pic: './music/pic/yinqueshiting.jpg',
            theme: '#ebd0c2'
        }, {
            title: '我曾',
            artist: '隔壁老樊',
            src: 'http://music.ruoyi.vip/woceng',
            pic: './music/pic/gebilaofan.jpg',
            theme: '#46718b'
        }, {
            title: '多想在平庸的生活拥抱你',
            artist: '隔壁老樊',
            src: 'http://music.ruoyi.vip/dxzpydshybn',
            pic: './music/pic/gebilaofan.jpg',
            theme: '#46718b'
        }, {
            title: '走马',
            artist: '摩登兄弟',
            src: 'http://music.ruoyi.vip/zouma',
            pic: './music/pic/modengxiongdi.jpg',
            theme: '#46718b'
        }, {
            title: '病变',
            artist: '江澈',
            src: 'http://music.ruoyi.vip/bingbian',
            pic: './music/pic/jiangche.jpg',
            theme: '#46718b'
        }, {
            title: '浪人琵琶',
            artist: '胡66',
            src: 'http://music.ruoyi.vip/langrenpipa',
            pic: './music/pic/hu66.jpg',
            theme: '#ebd0c2'
        }, {
            title: '芒种',
            artist: '赵方婧',
            src: 'http://music.ruoyi.vip/mangzhong',
            pic: './music/pic/zhaofangqian.jpg',
            theme: '#ebd0c2'
        }, {
            title: '逆流成河',
            artist: '金南玲',
            src: 'http://music.ruoyi.vip/niliuchenghe',
            pic: './music/pic/jinnanling.jpg',
            theme: '#ebd0c2'
        }, {
            title: '写给黄淮',
            artist: '张怡',
            src: 'http://music.ruoyi.vip/xiegeihuanghuai',
            pic: './music/pic/zhangyi.jpg',
            theme: '#ebd0c2'
        }, {
            title: '东西',
            artist: '林俊呈',
            src: 'http://music.ruoyi.vip/dongxi',
            pic: './music/pic/linjunchen.jpg',
            theme: '#46718b'
        }, {
            title: '选择失忆',
            artist: '季彦霖',
            src: 'http://music.ruoyi.vip/xuanzeshiyi',
            pic: './music/pic/bukaopu.jpg',
            theme: '#ebd0c2'
        }, {
            title: '38度6',
            artist: '黑龙',
            src: 'http://music.ruoyi.vip/38du6',
            pic: './music/pic/heilong.jpg',
            theme: '#ebd0c2'
        }, {
            title: '童话镇',
            artist: '陈一发',
            src: 'http://ruoyi.vip/music/mp3/陈一发 - 童话镇.mp3',
            pic: './music/pic/chenyifa.jpg',
            theme: '#ebd0c2'
        }, {
            title: '夜之光',
            artist: '花姐',
            src: 'http://music.ruoyi.vip/yezhiguang',
            pic: './music/pic/huajie.jpg',
            theme: '#ebd0c2'
        }, {
            title: '那个人',
            artist: '周延英',
            src: 'http://music.ruoyi.vip/nageren',
            pic: './music/pic/zhouyanying.jpg',
            theme: '#ebd0c2'
        }, {
            title: '9420',
            artist: '麦小兜',
            src: 'http://music.ruoyi.vip/9420',
            pic: './music/pic/maixiaodou.jpg',
            theme: '#ebd0c2'
        }, {
            title: '春风吹',
            artist: '阿冷',
            src: 'http://music.ruoyi.vip/chuifengchui',
            pic: './music/pic/aleng.jpg',
            theme: '#ebd0c2'
        }, {
            title: '来自天堂的魔鬼',
            artist: '邓紫棋',
            src: 'http://music.ruoyi.vip/lzttdmg',
            pic: './music/pic/dengziqi.jpg',
            theme: '#ebd0c2'
        }, {
            title: '倒数',
            artist: '邓紫棋',
            src: 'http://music.ruoyi.vip/daoshu',
            pic: './music/pic/dengziqi.jpg',
            theme: '#ebd0c2'
        }, {
            title: '光年之外',
            artist: '邓紫棋',
            src: 'http://music.ruoyi.vip/guangnianzhiwai',
            pic: './music/pic/dengziqi.jpg',
            theme: '#ebd0c2'
        }, {
            title: '不再犹豫',
            artist: 'Beyond',
            src: 'http://music.ruoyi.vip/buzaiyouyu',
            pic: './music/pic/Beyond.jpg',
            theme: '#ebd0c2'
        }, {
            title: '大地',
            artist: 'Beyond',
            src: 'http://music.ruoyi.vip/dadi',
            pic: './music/pic/Beyond.jpg',
            theme: '#ebd0c2'
        }, {
            title: '光辉岁月',
            artist: 'Beyond',
            src: 'http://music.ruoyi.vip/guanghuisuiyue',
            pic: './music/pic/Beyond.jpg',
            theme: '#ebd0c2'
        }, {
            title: '海阔天空',
            artist: 'Beyond',
            src: 'http://music.ruoyi.vip/haikuotiankong',
            pic: './music/pic/Beyond.jpg',
            theme: '#ebd0c2'
        }, {
            title: '灰色轨迹',
            artist: 'Beyond',
            src: 'http://music.ruoyi.vip/huiseguiji',
            pic: './music/pic/Beyond.jpg',
            theme: '#ebd0c2'
        }, {
            title: '冷雨夜',
            artist: 'Beyond',
            src: 'http://music.ruoyi.vip/lengyeyu',
            pic: './music/pic/Beyond.jpg',
            theme: '#ebd0c2'
        }, {
            title: '情人',
            artist: 'Beyond',
            src: 'http://music.ruoyi.vip/qingren',
            pic: './music/pic/Beyond.jpg',
            theme: '#ebd0c2'
        }, {
            title: '谁伴我闯荡',
            artist: 'Beyond',
            src: 'http://music.ruoyi.vip/shuibanwochuangdang',
            pic: './music/pic/Beyond.jpg',
            theme: '#ebd0c2'
        }, {
            title: '喜欢你',
            artist: 'Beyond',
            src: 'http://music.ruoyi.vip/xihuanni',
            pic: './music/pic/Beyond.jpg',
            theme: '#ebd0c2'
        }, {
            title: '真的爱你',
            artist: 'Beyond',
            src: 'http://music.ruoyi.vip/zhendeaini',
            pic: './music/pic/Beyond.jpg',
            theme: '#ebd0c2'
        }, {
            title: 'The Spectre',
            artist: 'Alan Walker',
            src: 'http://music.ruoyi.vip/the-spectre',
            pic: './music/pic/AlanWalker.jpg',
            theme: '#46718b'
        },  {
            title: 'All Falls Down',
            artist: 'Alan Walker',
            src: 'http://music.ruoyi.vip/all-falls-down',
            pic: './music/pic/AlanWalker.jpg',
            theme: '#46718b'
        },  {
            title: 'Alone',
            artist: 'Alan Walker',
            src: 'http://music.ruoyi.vip/alone',
            pic: './music/pic/AlanWalker.jpg',
            theme: '#46718b'
        }, {
            title: 'Faded',
            artist: 'Alan Walker',
            src: 'http://music.ruoyi.vip/faded',
            pic: './music/pic/AlanWalker.jpg',
            theme: '#46718b'
        }, {
            title: 'PDD 洪荒之力',
            artist: 'Hoaprox',
            src: 'http://music.ruoyi.vip/honghuanzhili',
            pic: './music/pic/Hoaprox.jpg',
            theme: '#46718b'
        }, {
            title: 'Kattrina',
            artist: 'Fly Project',
            src: 'http://music.ruoyi.vip/kattrina',
            pic: './music/pic/FlyProject.jpg',
            theme: '#46718b'
        }, {
            title: 'Zuehlsdorff',
            artist: 'Vicetone',
            src: 'http://music.ruoyi.vip/way-back',
            pic: './music/pic/Vicetone.jpg',
            theme: '#46718b'
        }, {
            title: 'Run Free',
            artist: 'Deep Chills',
            src: 'http://music.ruoyi.vip/run-free',
            pic: './music/pic/DeepChills.jpg',
            theme: '#46718b'
        }, {
            title: 'Something Just Like This',
            artist: 'The Chainsmokers',
            src: 'http://music.ruoyi.vip/something-just-like-this',
            pic: './music/pic/TheChainsmokers.jpg',
            theme: '#46718b'
        }, {
            title: 'Wild',
            artist: 'Monogem',
            src: 'http://music.ruoyi.vip/wild',
            pic: './music/pic/Monogem.jpg',
            theme: '#46718b'
        }, {
            title: 'Sunshine Girl',
            artist: 'Moumoon',
            src: 'http://music.ruoyi.vip/sunshine-girl',
            pic: './music/pic/Moumoon.jpg',
            theme: '#46718b'
        }, {
            title: 'Friendships (Original Mix)',
            artist: 'Pascal Letoublon',
            src: 'http://music.ruoyi.vip/friendships',
            pic: './music/pic/PascalLetoublon.jpg',
            theme: '#46718b'
        }, {
            title: 'Williams - Lullaby',
            artist: 'R3hab,Mike',
            src: 'http://music.ruoyi.vip/lullaby',
            pic: './music/pic/R3hab.jpg',
            theme: '#46718b'
        }, {
            title: 'Move Your Body (Alan Walker Remix)',
            artist: 'Sia,Alan Walker',
            src: 'http://music.ruoyi.vip/move-your-body',
            pic: './music/pic/AlanWalker.jpg',
            theme: '#46718b'
        }, {
            title: 'Unity',
            artist: 'The Fat Rat',
            src: 'http://music.ruoyi.vip/unity',
            pic: './music/pic/TheFatRat.jpg',
            theme: '#46718b'
        }, {
            title: 'Seve',
            artist: 'Tez Cadey',
            src: 'http://music.ruoyi.vip/seve',
            pic: './music/pic/TezCadey.jpg',
            theme: '#46718b'
        }, {
            title: '一曲相思',
            artist: '阿悠悠',
            src: 'http://music.ruoyi.vip/yiquxiangsi',
            pic: './music/pic/ayouyou.jpg',
            theme: '#ebd0c2'
        }, {
            title: '流浪',
            artist: '半阳',
            src: 'http://music.ruoyi.vip/liulang',
            pic: './music/pic/banyang.jpg',
            theme: '#46718b'
        }, {
            title: '画',
            artist: '赵雷',
            src: 'http://music.ruoyi.vip/zlhua',
            pic: './music/pic/zhaolei.jpg',
            theme: '#46718b'
        }, {
            title: '说书人',
            artist: '暗杠,寅子',
            src: 'http://music.ruoyi.vip/shuoshuren',
            pic: './music/pic/angang.jpg',
            theme: '#46718b'
        }, {
            title: '不染',
            artist: '简弘亦',
            src: 'http://music.ruoyi.vip/buran',
            pic: './music/pic/jianhongyi.jpg',
            theme: '#46718b'
        }, {
            title: '陷阱',
            artist: '王北车',
            src: 'http://music.ruoyi.vip/xianjing',
            pic: './music/pic/wangbeiche.jpg',
            theme: '#46718b'
        }, {
            title: '遥远的你',
            artist: '不靠谱组合',
            src: 'http://music.ruoyi.vip/yaoyuandeni',
            pic: './music/pic/bukaopu.jpg',
            theme: '#ebd0c2'
        }, {
            title: '月牙湾',
            artist: '刘至佳',
            src: 'http://music.ruoyi.vip/yueyawan',
            pic: './music/pic/liuzhijia.jpg',
            theme: '#ebd0c2'
        }, {
            title: '去年夏天',
            artist: '王大毛',
            src: 'http://music.ruoyi.vip/qunianxiatian',
            pic: './music/pic/wangdamao.jpg',
            theme: '#46718b'
        }, {
            title: '带你去旅行',
            artist: '校长',
            src: 'http://music.ruoyi.vip/dainiqulvxing',
            pic: './music/pic/xiaozhang.jpg',
            theme: '#46718b'
        }, {
            title: '心如止水',
            artist: 'Ice Paper',
            src: 'http://music.ruoyi.vip/xinruzhishui',
            pic: './music/pic/IcePape.jpg',
            theme: '#46718b'
        }, {
            title: '侧脸',
            artist: '于果',
            src: 'http://music.ruoyi.vip/celian',
            pic: './music/pic/yuguo.jpg',
            theme: '#ebd0c2'
        }, {
            title: '绿色',
            artist: '陈雪凝',
            src: 'http://music.ruoyi.vip/lvse',
            pic: './music/pic/chenxuening.jpg',
            theme: '#ebd0c2'
        }, {
            title: '出山',
            artist: '花粥',
            src: 'http://music.ruoyi.vip/chushan',
            pic: './music/pic/huazhou.jpg',
            theme: '#ebd0c2'
        }, {
            title: '遥不可及的你',
            artist: '花粥',
            src: 'http://music.ruoyi.vip/yaobukejideni',
            pic: './music/pic/huazhou.jpg',
            theme: '#ebd0c2'
        }, {
            title: '相思如意',
            artist: '兔子牙',
            src: 'http://music.ruoyi.vip/xiangsiruyi',
            pic: './music/pic/tuziya.jpg',
            theme: '#505d6b'
        }, {
            title: '江南夜色',
            artist: '程响',
            src: 'http://music.ruoyi.vip/jiangnanyese',
            pic: './music/pic/chengxiang.jpg',
            theme: '#46718b'
        }, {
            title: '过客',
            artist: '周思涵',
            src: 'http://music.ruoyi.vip/guoke',
            pic: './music/pic/zhousihan.jpg',
            theme: '#505d6b'
        }, {
            title: '年少有为',
            artist: '李荣浩',
            src: 'http://music.ruoyi.vip/nianshaoyouwei',
            pic: './music/pic/lironghao.jpg',
            theme: '#46718b'
        }, {
            title: '曾经的你',
            artist: '许巍',
            src: 'http://music.ruoyi.vip/cengjingdeni',
            pic: './music/pic/xuwei.jpg',
            theme: '#46718b'
        }, {
            title: '出现又离开',
            artist: '梁博',
            src: 'http://music.ruoyi.vip/chuxianyoulikai',
            pic: './music/pic/liangbo.jpg',
            theme: '#46718b'
        }, {
            title: 'A Little Story',
            artist: 'Valentin',
            src: 'http://music.ruoyi.vip/a-little-story',
            pic: './music/pic/Valentin.jpg',
            theme: '#46718b'
        }]
    }
};
